// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package product

import (
	"context"

	"github.com/shopspring/decimal"
)

type Querier interface {
	CreateProduct(ctx context.Context, storeID int32, categoryID int32, name string, brand *string, slug string, shortInfo []string, imageUrls ImageUrls, specs Specs, status ProductStatus) (*Product, error)
	CreateProductAttribute(ctx context.Context, productID int64, attribute string) (int64, error)
	CreateProductPricing(ctx context.Context, productID int64, basePrice decimal.Decimal, currencyCode string, discountLevel decimal.Decimal, discountedAmount decimal.Decimal, isOnSale bool) error
	CreateSKU(ctx context.Context, productID int64, sku string, quantityInStock int32, hasSepPricing bool, imageRefs []int16) (int64, error)
	CreateSKUPricing(ctx context.Context, skuID int64, basePrice decimal.Decimal, currencyCode string, discountLevel decimal.Decimal, discountedAmount decimal.Decimal, isOnSale bool) (int64, error)
	CreateSKUProductAttributeValues(ctx context.Context, skuID int64, productAttributeID int64, attributeValue string) error
	GetProductAttributesByProductID(ctx context.Context, productID int64) ([]*GetProductAttributesByProductIDRow, error)
	GetProductByID(ctx context.Context, id int64) (*GetProductByIDRow, error)
	GetProductsByCategoryIDs(ctx context.Context, offset int32, limit int32, leafCategoryIds []int32) ([]*Product, error)
	GetSKUsByProductID(ctx context.Context, productID int64) ([]*GetSKUsByProductIDRow, error)
}

var _ Querier = (*Queries)(nil)
