// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user

import (
	"context"
)

type Querier interface {
	CreateSeller(ctx context.Context, email string, password string, fullName string, status UserStatus) (int64, error)
	CreateUser(ctx context.Context, email string, password string, fullName string, otp *string, otpExpiry *int64) error
	GetUser(ctx context.Context, id int64) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	UpdateUserStatus(ctx context.Context, status UserStatus, iD int64) error
}

var _ Querier = (*Queries)(nil)
