// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package payment

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type StripeCardPayment struct {
	ID               int64
	OrderID          int64
	UserID           *int64
	BillingAddressID int64
	PaymentIntentID  string
	PaymentMethodID  *string
	Amount           decimal.Decimal
	Currency         string
	Status           string
	ClientSecret     *string
	LastError        *string
	CardLast4        string
	CardBrand        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
