// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package payment

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Querier interface {
	Create(ctx context.Context, orderID int64, userID *int64, billingAddressID int64, paymentIntentID string, paymentMethodID *string, amount decimal.Decimal, currency string, status string, clientSecret *string, lastError *string, cardLast4 string, cardBrand string, createdAt pgtype.Timestamptz) error
	GetByOrderID(ctx context.Context, orderID int64) (*StripeCardPayment, error)
}

var _ Querier = (*Queries)(nil)
