// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package featured_promotion

import (
	"context"
)

type Querier interface {
	GetFeaturedPromotions(ctx context.Context, limit int32) ([]*GetFeaturedPromotionsRow, error)
}

var _ Querier = (*Queries)(nil)
