// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package featured_selection

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FeaturedSelection struct {
	ID           int64
	ResourcePath string
	BannerInfo   []byte
	ImageUrl     string
	QueryParams  []byte
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	DisplayOrder *int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
