// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package featured_selection

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Create(ctx context.Context, resourcePath string, bannerInfo []byte, imageUrl string, queryParams []byte, startDate pgtype.Date, endDate pgtype.Date, displayOrder *int32) (*FeaturedSelection, error)
	ListAllActive(ctx context.Context) ([]*FeaturedSelection, error)
}

var _ Querier = (*Queries)(nil)
