// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: collection.sql

package collection

import (
	"context"
)

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, handle, description FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id int32) (*Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handle,
		&i.Description,
	)
	return &i, err
}
