// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package collection

import (
	"context"
)

type Querier interface {
	GetCollectionByID(ctx context.Context, id int32) (*Collection, error)
}

var _ Querier = (*Queries)(nil)
