// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package order

import (
	"context"

	"github.com/shopspring/decimal"
)

type Querier interface {
	CountActiveOrders(ctx context.Context, userID *int64) (int64, error)
	CreateOrder(ctx context.Context, cartID int64, userID *int64, totalAmount decimal.Decimal, paymentIntentID string, shippingAddress []byte, billingAddress []byte) (*Order, error)
	CreateOrderItems(ctx context.Context, arg []CreateOrderItemsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
