// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: seller_store.sql

package sellerstore

import (
	"context"
)

const createStore = `-- name: CreateStore :one
INSERT INTO seller_stores (
    public_id, seller_id, name, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id
`

func (q *Queries) CreateStore(ctx context.Context, publicID string, sellerID int64, name string, description string) (int32, error) {
	row := q.db.QueryRow(ctx, createStore,
		publicID,
		sellerID,
		name,
		description,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
